#Travis CI

language: php

php:
 - 5.6

branches:
 - master

before_script:
 - mkdir plugins
 - wget -O plugins/DevTools.phar https://github.com/PocketMine/DevTools/releases/download/v1.9.0/DevTools_v1.9.0.phar
 - pecl install channel://pecl.php.net/pthreads-2.0.10
 - pecl install channel://pecl.php.net/weakref-0.2.6
 - echo | pecl install channel://pecl.php.net/yaml-1.1.1
 - wget https://github.com/cbednarski/pharcc/releases/download/v0.2.3/pharcc.phar
 - chmod +x pharcc.phar
 - sudo mv pharcc.phar /usr/local/bin/pharcc

script:
 - php tests/TravisTest.php
 - phpunit
 
notifications:
 email: false
 #webhooks: http://n.tkte.ch/h/214/wsNvmG43-ncxUVRrFPwSM-r0
