#Travis CI

language: php

php:
 - 5.6

branches:
 - master

before_script:
 - mkdir plugins
 - wget -O plugins/DevTools.phar https://github.com/PocketMine/DevTools/releases/download/v1.9.0/DevTools_v1.9.0.phar
 - pecl install channel://pecl.php.net/pthreads-2.0.10
 - pecl install channel://pecl.php.net/weakref-0.2.6
 - echo | pecl install channel://pecl.php.net/yaml-1.1.1

script:
 - php tests/TravisTest.php

deploy:
  provider: releases
  api_key: "89948a4469df10fb0fb3f5c1b2779eb9014b36ac"
  file: "/home/Travis/build/ImagicalCorp/PocketMine-0.13.0/plugins/DevTools//PocketMine-MP_1.7dev.phar"
  skip_cleanup: true
  on:
    tags: true
 
notifications:
 email: false
 #webhooks: http://n.tkte.ch/h/214/wsNvmG43-ncxUVRrFPwSM-r0
